### ISSUE TITLE
Create folder -->keyboard

### ISSUE THREAD

**Issue by Leekammi** [Scipiapps/board#3]
Create folder -->keyboard

return button---> Done button

**Comment by zedoul** [comment]
Fixed : Return -> Done
We can change the text into only one of pre-defined texts as follows : 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextInputTraits_Protocol/index.html#//apple_ref/c/tdef/UIReturnKeyType

Fortunately there is a "Done" text.
