### ISSUE TITLE
player에서 버튼들 한 5초뒤에 사라지게 하기

### ISSUE THREAD

**Issue by Leekammi** [Scipiapps/board#6]
player에서 버튼들 한 5초뒤에 사라지게 하기
지금은 여백 클릭해야 없어짐 -->자동으로 몇초뒤에 없어지게 하기
살짝 dim으로. 효과 넣기~

**Comment by zedoul** [comment]
1. NSTimer* _hudIdler 추가
2. showHUD의 animateWithDuration의 
completion에서 (BOOL) show==YES 인 경우 해당 timer 생성.
3. showHUD의 show==NO인 경우 해당 타이머 invalidate and assign nil
