### ISSUE TITLE
List / Edit뷰에서 디자인 사양 바꿈

### ISSUE THREAD

**Issue by Leekammi** [Scipiapps/board#9]
![1-2](https://cloud.githubusercontent.com/assets/4279952/6318436/a914b90a-ba92-11e4-805a-e95e873951d9.png)

Reference to attached images--

1. List - Emtyness color - White ---> Grey (RGB: 235,235,235)

2.List - Selected list color -----> white--> Blue (RGB: 239,244,255)

2-1. Select area : check box ---> whole part of cell

**Comment by zedoul** [comment]
done
